### ISSUE TITLE
Items all gone!

### ISSUE THREAD

**Issue by FatBiscuit** [DFreds/dfreds-pocket-change#12] opened 2021-04-04 13:44 UTC
I find when I use the macro to change an actor token to a loot sheet, the actor token often loses most of its items and my players and I am unable to open that actor's sheet at all.  I have to delete the token and place a new one.

**Comment by DFreds** [comment] 2021-04-07 00:13
I am not seeing this issue. Can you provide more information? Which macro are you running, which version of foundry, what kind of token, etc?

**Comment by DFreds** [comment] 2021-04-07 00:20
Also, any settings you have set for my module would be good too

**Comment by DFreds** [comment] 2021-04-07 00:37
![image](https://user-images.githubusercontent.com/11878569/113794114-d21ba080-9717-11eb-8b2e-0ec39abf8ef5.png)

Make sure that "Remove damaged items" is not checked. If you want to remove the damaged items feature all together, just set "Chance of damaged items" to 0.

**Comment by FatBiscuit** [comment] 2021-04-10 14:41
Foundry 0.7.9
DnD5e 1.2.4
I used the "Generate Currency and Convert to Loot for Selected Tokens" macro included in the module. 
It works some of the time, but occasionally when my players open the now-lootable token, they see nothing and I'm no longer able to open the loot sheet and all the items placed there are gone and/or inaccessible.

**Comment by DFreds** [comment] 2021-04-11 21:12
Hm, okay. I'll investigate further. Thanks for replying

**Comment by DFreds** [comment] 2021-04-11 21:20
Does this happen when you use the regular convert to loot macro (meaning not the one that also generates currency first)? Also, do you have currency generation enabled when you drop a token onto the canvas (the setting called Enabled)?

**Comment by DFreds** [comment] 2021-04-13 01:11
I'm unable to reproduce this issue, and need more information. My suggestion for a fix would be to reimport the macro from the DFreds Pocket Change compendium. You might have an old version or something. Feel free to post the code that is in the macro you're running that has the issue.

**Comment by DFreds** [comment] 2021-05-05 00:20
Closing due to lack of information

**Closed by DFreds** 2021-05-05 00:20 UTC
Labels: blocked
