### ISSUE TITLE
v10 version of Pocket Change not showing up on The Forge

### ISSUE THREAD

**Issue by weepingminotaur** [DFreds/dfreds-pocket-change#40] opened 2022-10-03 21:13 UTC
Last version available on the Forge is 3.2.1.

**Comment by DFreds** [comment] 2022-10-04 16:29
Is this the only one that is not showing up in the forge out of my modules for v10?

**Comment by weepingminotaur** [comment] 2022-10-04 16:32
Yep, the only one. Your other mods show up fine in the Forge.

**Comment by DFreds** [comment] 2022-10-04 19:58
This was caused by an old release of 4.0.0 back in December 2021 that I deleted. The Forge still had it picked up and hid it for me back then. This should be fixed now with 4.0.1

**Closed by DFreds** 2022-10-04 19:58 UTC
Labels: bug
