### ISSUE TITLE
GM must open actor sheet before changes are applied

### ISSUE THREAD

**Issue by alfredmakes** [DFreds/dfreds-pocket-change#5] opened 2021-01-22 15:32 UTC
Hello! Thank you for the excellent module. I'm using Foundry 0.7.9

When I use the _Generate Currency and Convert to Loot for Selected Tokens_ macro, if a player tries to access the generated LootSheet they get this error:
![image](https://user-images.githubusercontent.com/7167067/105509052-02c96d80-5cc5-11eb-91dd-e9665966e93a.png)

To avoid this, I must run the macro and then open each token's sheet one-by-one.

I'm not sure if this is a Foundry limitation or a module incompatibility on my end, if so I apologize for the bad ticket!

**Comment by DFreds** [comment] 2021-01-25 20:45
Thanks for reporting this! Sorry it took me a bit to get back to you. I'll check it out and see.

**Comment by DFreds** [comment] 2021-01-26 01:48
Hey @alfredmakes,

I was unable to reproduce this issue. My guess is something is conflicting with it. Make sure you have the latest LootSheetNPC5e and Pocket Change both enabled, and try it out with just those modules enabled. If it still doesn't work after that, let me know.

**Comment by DFreds** [comment] 2021-01-28 23:46
Reopening this because I was able to reproduce it with actors from the DnD5e compendium. I was not able to reproduce it with monsters created in the world itself. I'll have to look into why this is the case.

**Comment by DFreds** [comment] 2021-01-30 02:13
Resolved in v1.5.2. Let me know if any issues persist

**Closed by DFreds** 2021-01-30 02:13 UTC
Labels: bug
