### ISSUE TITLE
Damaged items macro not working

### ISSUE THREAD

**Issue by bugbeersandflagons** [DFreds/dfreds-pocket-change#21] opened 2021-08-27 19:12 UTC
I am using the custom damage macro, which I've just reimported from the compendium, and running version 3.1.2 of the module.  Using the damaged items settings under module settings, and generating loot from the character sheet, I still never see damaged items (even if set to 100% chance items will be damaged).

Similarly, if I use the macro and set the values to a high chance of damaged items, converting to lootable just puts the full value, undamaged items on the sheet for players to loot.

I am also running Monk's Token Bar, and Monk's Little Details - so not sure if there's some clash there since it also has a convert to loot function (which I've currently got disabled).

![macro](https://user-images.githubusercontent.com/85903357/131177489-6fafb4d6-c492-4833-b34d-fc52520b4781.PNG)
![loot sheet](https://user-images.githubusercontent.com/85903357/131177494-f433fa53-74f4-4c5e-845b-64f86d25ff04.PNG)

**Comment by DFreds** [comment] 2021-08-29 20:13
Hm, thanks for bringing this up. I highly doubt there is any clashing going on with any other module. I'll try to see if I can reproduce this. Just to be clear, you're converting to loot only with the custom macro and not the button on the character sheet?

What happens if you go into the pocket change settings and set the damaged item values really high there and use the button on the character sheet to convert it to a lootable?

**Comment by DFreds** [comment] 2021-08-31 00:15
I'm unable to reproduce this issue. Best bet is to copy/paste the entire macro you're running here so I can see if I see anything funky. But otherwise, it seems to be working exactly as expected. You could also try disabling all other modules to see if something is conflicting. Feel free to get back to me, but I'm closing this for now.

**Closed by DFreds** 2021-08-31 00:15 UTC
Labels: bug

**Comment by bugbeersandflagons** [comment] 2021-08-31 12:20
// This is the percent chance that a Common item will be damaged when a token is converted to loot. A damaged item has its value reduced and appends (Damaged) to the name. Set this to 0 if you want to disable damaged items.
const chanceOfDamagedItems = 1.0;

// This multiplies the price of a damaged item by the given number, lowering its value.
const damagedItemsMultiplier = 0.1;

// If set to true, this will remove items that are damaged from tokens that are converted to loot.
const removeDamagedItems = false;

const macroSupport = new game.dfreds.MacroSupport();
macroSupport.convertSelectedTokensToLoot(
  chanceOfDamagedItems,
  damagedItemsMultiplier,
  removeDamagedItems
);

Above is the macro.  Changing the settings in the options and using the button on the character sheet has the same result - no damaged items.  I'll try running this with no other modules as you suggest

**Comment by bugbeersandflagons** [comment] 2021-08-31 13:40
Right... so this seems to depend on the compendium I've imported from.  I have a large compendium of actors I tend to draw from, and the macro does not work on those.  However, importing directly from the SRD compendium, the macro works. 

I'm fairly satisfied this is an issue with my actors, and not with your module!  I'll update here if I figure anything else out

**Comment by DFreds** [comment] 2021-08-31 16:28
Ah okay. Yeah, something must've gone wrong with the migration. Thanks for letting me know!

**Comment by asciodev** [comment] 2021-09-06 21:00
I am not getting any items converted to "Damaged" even when importing directly from the SRD compendium. Notably, when I import any monster from the SRD and check its features tab, the items have no set rarity value, for some reason. As a result, the check for "Common" items does not work on SRD compendium monsters.

This is definitely an issue with the SRD compendium and not this module. However, said issue completely prevents this feature (damaged items) of this module from working. I am not sure how to fix this.

**Comment by DFreds** [comment] 2021-09-07 13:27
Well, features shouldn't have a rarity... only inventory items. Is that what you meant?
